### ISSUE TITLE
Data Analysis Tutorials

### ISSUE THREAD

**Issue by HannahSi** [AguaClara/team_resources#5]
The [Example Code for Data Analysis](https://github.com/AguaClara/team_resources/blob/master/Example%20Code/Data%20Analysis.md) document in the Example Code folder currently has examples for using various tools and methods related to data analysis in Python. We may need to add more in-depth instructions, however, for members who have little experience with Python. Here are some modified outlines for the different sections:

**Reading Spreadsheet Data with Pandas**
* Reading data from a data file as a DataFrame object, using pandas.read_csv
  - include setting the right delimiter (ProCoDa files, even though they end with .xls, are actually CVS files with tab ("\t") delimiters
* Indexing rows, columns, and individual cells from the DataFrame
* Explaining DataFrame and Series data types
* converting Series to numeric data (pandas.Series.to_numeric?)
* Performing mathematical operations or functions on every element of a series

**Comment by elenapertsalis** [comment]
For more in-depth instructions, we created a PowerPoint on these topics that we will be presenting to Research and Fab teams on April 22th. We've also prepared practice questions for students to practice the skills.
